language: bash
sudo: false

addons:
  apt:
    packages:
      - libc6-i386
      - clisp

os:
  - linux
  - osx
  - windows

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  jobs:
    - LISP=sbcl-bin
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=clisp
    - LISP=ecl
    - LISP=cmucl
    - LISP=alisp

jobs:
  fast_finish: true
  include:
    - os: linux
      arch: arm64
      env: LISP=sbcl-bin
    - os: linux
      arch: ppc64le
      env: LISP=sbcl-bin
    - os: linux
      arch: arm64
      env: LISP=ccl-bin
  allow_failures:
    - env: LISP=abcl 
    - env: LISP=clisp
    - env: LISP=ecl  
    - env: LISP=cmucl
    - env: LISP=alisp
    - arch: arm64
    - arch: ppc64le
    - os: windows
    - os: osx

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - ( cd ~/lisp/ ; git clone https://github.com/guicho271828/lisp-namespace.git )
  - ( cd ~/lisp/ ; git clone https://github.com/guicho271828/type-i.git )
  - ( cd ~/lisp/ ; git clone https://github.com/guicho271828/type-r.git )
  - ( cd ~/lisp/ ; git clone https://github.com/guicho271828/trivia.git )
  - ( cd ~/lisp/ ; git clone https://github.com/numcl/constantfold.git )
  - ( cd ~/lisp/ ; git clone https://github.com/numcl/gtype.git )
  - ( cd ~/lisp/ ; git clone https://github.com/numcl/specialized-function.git )

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

script:
  - ./testscr.ros
